### ISSUE TITLE
Question about the data

### ISSUE THREAD

**Issue by Adele0108** [HieuPhan33/MaskGAN#1]
Hello, I have read your paper and find it very exciting, and I am trying corresponding experiments. 

Is the pre-processed data format 3d or 2d? Could you please provide the original MRI and CT data as well as the corresponding data and mask files obtained after preprocessing?

It is possible to provide just a few sample files if this is not convenient. Looking forward to your reply!

**Comment by hieuvmphan** [comment]
Hi, thanks for being interested in our work.

Unfortunately, the dataset is private and we don't have ethics approval to share. Sorry!

You can organize your 3D custom dataset, or any 3D public datasets in this structure: https://github.com/HieuPhan33/MaskGAN/blob/master/preprocess/README.md#data-preparation.

And run `preprocess/main.py` to convert 3d to 2d formats, along with the mask extraction.
