### ISSUE TITLE
Ask about the std+-deviation 

### ISSUE THREAD

**Issue by TMDTom** [HieuPhan33/MaskGAN#10]
Hello, I'm again. I want to know this meaning.
MaskGAN are also reported. ± standard deviation is reported over five evaluations. The paired t-test is conducted between MaskGAN and a compared method at p =0.05.
The five evaluations is meaning: train five times on the same dataset with same split? 
Thanks for your answer.

**Comment by victorcaquilpan** [comment]
Yes, the same dataset using same split :)!

**Comment by TMDTom** [comment]
> Yes, the same dataset using same split :)!

Thanks for your answer. The ablation experiment is also do like this? Thanks very mush.

**Comment by victorcaquilpan** [comment]
Yes

**Comment by TMDTom** [comment]
> Yes

Thanks a lot for your answer.

**Comment by TMDTom** [comment]
> Yes

Hello, thank you for your answer last time. I would like to understand it in more detail. Does the five experiments in the article mean that the data division results of each experiment are consistent, rather than the division rules are the same? For example, [1 2 3 4 5] is divided into [1 2 3 4] for training and [5] for testing, and this is repeated five times. Instead of the first experiment [1 2 3 4] training, the second experiment [1 2 3 5] training, and the third experiment [1 2 4 5] for training? Sorry to bother you again~

**Comment by victorcaquilpan** [comment]
Hi @TMDTom, the experiments don't consider cross-validation. So, from the beginning, we are using the same split of train and test. We use a small validation subset, which is just used to monitor the evolution of the training, however, the metrics reported in the paper are based on the test split.

**Comment by TMDTom** [comment]
> Hi @TMDTom, the experiments don't consider cross-validation. So, from the beginning, we are using the same split of train and test. We use a small validation subset, which is just used to monitor the evolution of the training, however, the metrics reported in the paper are based on the test split.
OK, thank you very much for your answer. This will help me with my experiment. Thanks again sincerely~
