### ISSUE TITLE
Some questions about datasets~

### ISSUE THREAD

**Issue by zky0701** [HieuPhan33/MaskGAN#11]
Hello author, thank you for your wonderful work. I have some questions regarding the preprocessing of the dataset. I am using my own dataset, and during data preprocessing, I found that the network is an unsupervised generative network. However, paired MR and CT data are required for data preprocessing. I would like to ask why this step is necessary? Will there be any problems if there is no paired CT data? Also, does paired data refer to registering CT data based on MR data? Looking forward to your answer!

**Comment by victorcaquilpan** [comment]
Hi @zky0701. MaskGAN is working over **unpaired data**. Our preprocessing mostly arrange the dimensions of images, put them in the same resolution, remove part of the background. Its not a registration process. Mostly we are just trying to align them.

**Comment by zky0701** [comment]
> Hi @zky0701. MaskGAN is working over **unpaired data**. Our preprocessing mostly arrange the dimensions of images, put them in the same resolution, remove part of the background. Its not a registration process. Mostly we are just trying to align them.

Thank you very much for your reply. I apologize for bothering you again. Yes, I know data preprocessing is not a registration job. I just want to know if I can still use this network to train my own dataset without paired CT data? Look forward to your reply.

**Comment by victorcaquilpan** [comment]
yes, absolutely you can do it. I mean that by saying "unpaired data" in this context.

**Comment by zky0701** [comment]
> yes, absolutely you can do it. I mean that by saying "unpaired data" in this context.

Okay, I understand now!Thank you so much for your reply!
