### ISSUE TITLE
Some questions about data preprocessing~

### ISSUE THREAD

**Issue by zky0701** [HieuPhan33/MaskGAN#12]
Hi! thank you very much for your wonderful work. I encountered a small problem during data preprocessing. My dataset is about lung magnetic resonance imaging, and my goal was to obtain cross-sectional PNG images after data preprocessing. I have made many code modifications, but the results have always been sagittal images. May I ask which part of the code should I modify? I am looking forward to your answer! (I previously attempted to modify the np.transpose and def save_slice sections)

**Comment by victorcaquilpan** [comment]
Hi @zky0701. Did you already solve that? if you want to obtain slices in a different orientation, you can modify the index used to crop the images. For example image[100,:,:] provides the 100th saggital slice, but image[0:100,:] could provide the 100th axial slice and so on. Depending on the orientation of your input images and on which orientation you want to do the training/inference.

**Comment by zky0701** [comment]
> Hi @zky0701. Did you already solve that? if you want to obtain slices in a different orientation, you can modify the index used to crop the images. For example image[100,:,:] provides the 100th saggital slice, but image[0:100,:] could provide the 100th axial slice and so on. Depending on the orientation of your input images and on which orientation you want to do the training/inference.

Yes, I have already solved it. Thank you very much for your answer!
