### ISSUE TITLE
a question about test

### ISSUE THREAD

**Issue by zky0701** [HieuPhan33/MaskGAN#13]
Hi~I found that the error came from the missing test.model file during testing. How can I modify the code? Looking forward to your reply!
![微信截图_20241213122750](https://github.com/user-attachments/assets/6c994383-924a-49ef-b954-15850f400ef8)

**Comment by zky0701** [comment]
> _No description provided._

Hello, I found that the error came from the missing test.model file during testing. How can I modify the code? Looking forward to your reply!
![微信截图_20241213122750](https://github.com/user-attachments/assets/102f0f04-e076-4a1e-9bdd-eb3f0d253018)

**Comment by zky0701** [comment]
> Hi~I found that the error came from the missing test.model file during testing. How can I modify the code? Looking forward to your reply! ![微信截图_20241213122750](https://private-user-images.githubusercontent.com/173424843/395428867-6c994383-924a-49ef-b954-15850f400ef8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNjY0MDMsIm5iZiI6MTczNDA2NjEwMywicGF0aCI6Ii8xNzM0MjQ4NDMvMzk1NDI4ODY3LTZjOTk0MzgzLTkyNGEtNDllZi1iOTU0LTE1ODUwZjQwMGVmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QwNTAxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGViNWQ4MzQwMjk0ZWEyZTU5YzQyMThjM2NjNTY1NTM5ZjAwY2RiNDU0YjM1OWRlNzA2NTgyZmRjYTllMDY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Niy1Cs_tPPH94izD0aNdRT9-rliZ-Wzh0zKqqT_y6XY)

Oh! I have identified my mistake and I have resolved it. I apologize for disturbing you due to my basic mistake. I am sooooooo sorry~

**Comment by victorcaquilpan** [comment]
Thanks @zky0701 !!!
