### ISSUE TITLE
Running train.py

### ISSUE THREAD

**Issue by fatemeh-phd76** [HieuPhan33/MaskGAN#3]
Hello again;
i am created root file that contain 2 folders named MRI and US.
each one contains 20 paired 3D images normalized *.npy. i changed directory and structure in main.py as you said. but i cant run train.py yet.
Could you please tell me where should i change the code to fix it?

**Comment by hieuvmphan** [comment]
Hi, my code expects 2D images in jpg and jpeg format.

Can you try preprocessing and extracting 2D slices using the code here: https://github.com/HieuPhan33/MaskGAN/tree/master/preprocess
