### ISSUE TITLE
About data

### ISSUE THREAD

**Issue by HilbertMaximov** [HieuPhan33/MaskGAN#4]
Dear author, hello. I noticed that your data seems to be sliced from 3D nii and saved in image format. My datasets (CT and MR) are both in PNG format. Can you tell me the specific processing method? Also, could you describe the folder arrangement of the processed dataset? For example, for specific methods like datasets/trainA or trainB like Cyclegan, could you please take a screenshot if it's convenient? This can keep your private data confidential.
Thank you very much!

**Comment by hieuvmphan** [comment]
Hi sorry for the late reply,

We only need to apply preprocessing to convert 3D to PNG. If you already have PNG. Please go ahead to train the model.

The exampled data folder structure is as below:

train_A
| ------- img1.png
| ------- img2.png
train_B
| ------- img1.png
| ------- img2.png
val_A
| ------- img3.png
| ------- img4.png
val_B
| ------- img3.png
| ------- img4.png
test_A
| ------- img5.png
| ------- img6.png
test_B
| ------- img5.png
| ------- img6.png
